### PR TITLE
map(f, t): create Columns when `f` returns tuple / named tuple

### PR DESCRIPTION
**Pull request by shashi**
Turned out to be a bit complicated...

addresses #52

### CODE REVIEW

**Comment by davidanthoff** [comment]
Should a map that returns a ``Pair{NamedTuple{...}, NamedTuple{...}}`` return an ``IndexedTable`` where the columns in the key of the pair make up the index, and the columns in the value make up the data columns? This would essentially be #55, but it would use a normal ``map`` as the API.

In some sense, all we would need is a constructor for ``IndexedTable`` that takes an iterator of that element type. That is something I wanted to add for some while: davidanthoff/IterableTables.jl#26

**Comment by shashi** [comment]
> Should a map that returns a Pair{NamedTuple{...}, NamedTuple{...}} return an IndexedTable where the columns in the key of the pair make up the index, and the columns in the value make up the data columns?

I don't think so... `map` should only work on values. You could have output keys that collide allowing you to implement `filter` with map which seems wrong.

>  a constructor for IndexedTable that takes an iterator of that element type

Good idea to add this... One could even convert any Associative to an IndexedTable just by calling this constructor.

**Comment by shashi** [comment]
An alternative approach using `Base.promote_op` is in #57

**Comment by shashi** [comment]
```julia
t = IndexedTable([1,2,3], Columns(x=[4,5,6]))
y = [1, 1//2, "x"]
t4 = map(x->(x.x, y[x.x-3]), t)
```
This doesn't work with the alternative approach as `promote_op` has difficulty figuring out the output type. Creating a function with return type annotation also didn't work...

**Comment by shashi** [comment]
> has difficulty figuring out the output type

Turns out it was throwing away the fact that the results are tuples when any field is UnionAll... Fixed in #57

**Pull request closed without merging**
